
export const SET_CLASS_LIST = 'SET_CLASS_LIST';
export const SET_CURRENT_CLASS_ID = 'SET_CURRENT_CLASS_ID';
export const SET_CHILD_INFO = 'SET_CHILD_INFO';
export const SET_LATEST_REMARK = 'SET_LATEST_REMARK';
export const SET_LATEST_CHECK = 'SET_LATEST_CHECK';

export const SET_TEMPLATE_COMPLETE = 'SET_TEMPLATE_COMPLETE';
export const SET_PROJECT_COMPLETE = 'SET_PROJECT_COMPLETE';

