
export const SET_CLASS_LIST = 'SET_CLASS_LIST';
export const SET_CURRENT_CLASS_ID = 'SET_CURRENT_CLASS_ID';
export const SET_CHILD_INFO = 'SET_CHILD_INFO';
export const SET_LATEST_REMARK = 'SET_LATEST_REMARK';
export const SET_LATEST_CHECK = 'SET_LATEST_CHECK';

export const SET_DEFAULT_PRAISE_IDS = 'SET_DEFAULT_PRAISE_IDS';
export const SET_DEFAULT_CRITICIZE_IDS = 'SET_DEFAULT_CRITICIZE_IDS';
export const SET_DEFAULT_SCHEDULE_IDS = 'SET_DEFAULT_SCHEDULE_IDS';
export const SET_DEFAULT_COURSE_IDS = 'SET_DEFAULT_COURSE_IDS';
