export const SET_GROUP_LIST = 'SET_GROUP_LIST';

export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';

export const SET_STUDENT_OF_GROUP = 'SET_STUDENT_OF_GROUP';

export const IS_REMARK_GROUP = 'IS_REMARK_GROUP';

export const SET_REMARK_GROUP_STUDENT_IDS = 'SET_REMARK_GROUP_STUDENT_IDS';
