export const SET_STUDENT_LIST = 'SET_STUDENT_LIST';

export const ADD_STUDENT_LIST = 'ADD_STUDENT_LIST';

export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT';

export const SET_STUDENT_REMARK_INFO = 'SET_STUDENT_REMARK_INFO';

export const SET_STUDENT_REMARK_LIST = 'SET_STUDENT_REMARK_LIST';
