export const SET_MASTER_CLASS_LIST = 'SET_MASTER_CLASS_LIST';

export const SET_TEACHER_CLASS_LIST = 'SET_TEACHER_CLASS_LIST';

export const SET_NOTICE_LIST = 'SET_NOTICE_LIST';

export const SET_HOMEWORK_LIST = 'SET_HOMEWORK_LIST';

export const SET_ALL_INFO_LIST = 'SET_ALL_INFO_LIST';

export const SET_RATE_INFO = 'SET_RATE_INFO';
